<a href="https://colab.research.google.com/github/abstruse020/musicMan/blob/master/musicMan_for_flask_application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.nn.parallel
import matplotlib.pyplot as plt
import csv

In [0]:
triplets_file='https://static.turi.com/datasets/millionsong/10000.txt'
songs_metadata_file = 'https://static.turi.com/datasets/millionsong/song_data.csv'

In [0]:
song_df_1 = pd.read_table(triplets_file,header=None)
song_df_1.columns = ['user_id', 'song_id', 'listen_count']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  """Entry point for launching an IPython kernel.


In [0]:
song_df_1.head()

user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1

user_id             song_id  listen_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995             1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B             2
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBXHDL12A81C204C0             1
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBYHAJ12A6701BF1D             1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SODACBL12A8C13C273             1

In [0]:

song_df_2 =  pd.read_csv(songs_metadata_file)

song_df = pd.merge(song_df_1, song_df_2.drop_duplicates(['song_id']), on="song_id", how="left")

In [0]:
song_df_2.head()

song_id              title  ...       artist_name  year
0  SOQMMHC12AB0180CB8       Silent Night  ...  Faster Pussy cat  2003
1  SOVFVAK12A8C1350D9        Tanssi vaan  ...  Karkkiautomaatti  1995
2  SOGTUKN12AB017F4F1  No One Could Ever  ...    Hudson Mohawke  2006
3  SOBNYVR12A8C13558C      Si Vos Querés  ...       Yerba Brava  2003
4  SOHSBXH12A8C13B0DF   Tangle Of Aspens  ...        Der Mystic     0

[5 rows x 5 columns]

song_id              title  ...       artist_name  year
0  SOQMMHC12AB0180CB8       Silent Night  ...  Faster Pussy cat  2003
1  SOVFVAK12A8C1350D9        Tanssi vaan  ...  Karkkiautomaatti  1995
2  SOGTUKN12AB017F4F1  No One Could Ever  ...    Hudson Mohawke  2006
3  SOBNYVR12A8C13558C      Si Vos Querés  ...       Yerba Brava  2003
4  SOHSBXH12A8C13B0DF   Tangle Of Aspens  ...        Der Mystic     0

[5 rows x 5 columns]

In [0]:
song_df_2[song_df_2['song_id']== 'SOQMMHC12AB0180CB8']

song_id         title  ...       artist_name  year
0  SOQMMHC12AB0180CB8  Silent Night  ...  Faster Pussy cat  2003

[1 rows x 5 columns]

song_id         title  ...       artist_name  year
0  SOQMMHC12AB0180CB8  Silent Night  ...  Faster Pussy cat  2003

[1 rows x 5 columns]

In [0]:
song_df.head()

user_id  ...  year
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...     0
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...  1976
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...  2007
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...  2005
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...  1999

[5 rows x 7 columns]

user_id  ...  year
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...     0
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...  1976
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...  2007
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...  2005
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...  1999

[5 rows x 7 columns]

In [0]:
print(song_df.shape)

(2000000, 7)
(2000000, 7)


selecting a subset of main data

In [0]:
songs_data = song_df.iloc[:10000,:3]
#songs_data.head()
songs_data.shape

(10000, 3)

(10000, 3)

For saving the songs 

In [0]:
save_songs_data = song_df.iloc[:10000,:4]
#songs_data.head()
save_songs_data.shape

(10000, 4)

(10000, 4)

#spliting the data

In [0]:
#songs_data_train, songs_data_test, _, _ = train_test_split(songs_data,songs_data[:,0],test_size =0.20, random_state = 1)

In [0]:
#songs_data_test.head()
#print(songs_data_test.size,songs_data_train.size)

In [0]:
grouped_songs = songs_data.groupby('user_id')

In [0]:
save_grouped_songs = save_songs_data.groupby('song_id')

In [0]:
no_users=0
users = []
for key,data in grouped_songs:
  #print("Key ",key)
  #print("\nData ",data)
  no_users+=1
  users.append(key)

In [0]:
print(no_users,users)

365 ['0152fcbd02b172a874c75a57a913f0f0109ba272', '01655ae6bc52e29c9cd100a7dde4e9eeae5e4031', '03c90bfd09151973863c4cadd5a749cd7982abc0', '0560337e6a33be7149c9568b5fde5788294fe101', '06b31818386e598017a475f8e349b3ca31ba3178', '07caa920795cd4f20bfeeb0e192a5ddd9566ecdd', '08c129083a44492415e40b70d8f90755e15f4a91', '0a00498b9d607844a8826184ae7278097d1c008a', '0a004c08b700e4edb74b44c2dbceca4280760a9a', '0afaa5d9d04bf85af720fe8cc566a41ca3e41c97', '0c1a6a1fc9b0e6df616c5bddace2559a7952ebe5', '0c306ce1440dec3b5b07b425880e43b4fb66fe93', '0dd93f61fe69f292ac336715ef607214efb3dbaa', '0e695c8614e9d76a157f39d4b30e7b076d3f3147', '0eda271c8bf8b846c1c0320f6b7656ca73b80992', '0ef42a19efb74d0a05c308d00636c8d8d41bec0c', '1012ecfd277b96487ed8357d02fa8326b13696a5', '116a4c95d63623a967edf2f3456c90ebbf964e6f', '12497e138741a0b94bb36a14bef32c9d0ee20fec', '12768858f6a825452e412deb1df36d2d1d9c6791', '12a4a991c8b53cd6906995caed8b1f2bd3b6436a', '135ae184f8552252dcdec7f82ff6f647fa76e9ec', '14903f6491e335f4c5f9c42573

collecting songs
making a list of songs

In [0]:
grouped_songs_2 = songs_data.groupby('song_id')
grouped_songs_2.head()

user_id  ... listen_count
0     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
1     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            2
2     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
3     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
4     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
5     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            5
6     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
7     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
8     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
9     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
10    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
11    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            5
12    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
13    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
14    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            5
15    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
16    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            6
17    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
18    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
19    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
20    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
21    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
22    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
23    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
24    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
25    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
26    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
27    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
28    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
29    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            2
...                                        ...  ...          ...
9964  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            4
9966  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9967  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9968  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            5
9970  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            9
9971  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...           15
9972  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            2
9973  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            2
9975  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...           36
9976  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            7
9977  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            2
9978  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            2
9979  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9981  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9984  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            3
9985  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            4
9986  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9987  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            5
9988  08c129083a44492415e40b70d8f90755e15f4a91  ...            5
9989  08c129083a44492415e40b70d8f90755e15f4a91  ...           12
9990  08c129083a44492415e40b70d8f90755e15f4a91  ...            1
9991  08c129083a44492415e40b70d8f90755e15f4a91  ...            1
9992  08c129083a44492415e40b70d8f90755e15f4a91  ...            2
9993  08c129083a44492415e40b70d8f90755e15f4a91  ...            1
9994  08c129083a44492415e40b70d8f90755e15f4a91  ...            1
9995  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            2
9996  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            5
9997  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            5
9998  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            5
9999  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            5

[9072 ro

user_id  ... listen_count
0     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
1     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            2
2     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
3     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
4     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
5     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            5
6     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
7     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
8     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
9     b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
10    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
11    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            5
12    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
13    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
14    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            5
15    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
16    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            6
17    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
18    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
19    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
20    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
21    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
22    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
23    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
24    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
25    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
26    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
27    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
28    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            1
29    b80344d063b5ccb3212f76538f3d9e43d87dca9e  ...            2
...                                        ...  ...          ...
9964  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            4
9966  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9967  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9968  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            5
9970  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            9
9971  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...           15
9972  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            2
9973  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            2
9975  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...           36
9976  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            7
9977  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            2
9978  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            2
9979  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9981  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9984  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            3
9985  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            4
9986  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            1
9987  bf03bbb01a7803ed1a5fec51bfe9423a79737d1a  ...            5
9988  08c129083a44492415e40b70d8f90755e15f4a91  ...            5
9989  08c129083a44492415e40b70d8f90755e15f4a91  ...           12
9990  08c129083a44492415e40b70d8f90755e15f4a91  ...            1
9991  08c129083a44492415e40b70d8f90755e15f4a91  ...            1
9992  08c129083a44492415e40b70d8f90755e15f4a91  ...            2
9993  08c129083a44492415e40b70d8f90755e15f4a91  ...            1
9994  08c129083a44492415e40b70d8f90755e15f4a91  ...            1
9995  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            2
9996  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            5
9997  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            5
9998  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            5
9999  15cc706a7f24975ca831aaaf297bf0392746b3fe  ...            5

[9072 ro

In [0]:
no_songs = 0
songs = []
for key,data in grouped_songs_2:
  #print('key',key)
  #print('\ndata',data)
  no_songs+=1
  songs.append(key)
#songs = set(songs)

In [0]:
print(no_songs,len(songs))

5175 5175
5175 5175


In [0]:
req_songs = song_df_2[song_df_2['song_id'].isin(songs)]

req_songs['user_like']=0
req_songs.head()


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


song_id                                title  ...  year user_like
245   SOSZNRJ12A8AE46E38                  Anyone Else But You  ...  2007         0
412   SOGKGLB12A81C22AFA                  Drunk and Hot Girls  ...  2007         0
484   SOQBGZD12AB0184341                        Rewind (Demo)  ...     0         0
809   SOOLSML12A8C1414DC  Don't Upset The Rhythm (Go Baby Go)  ...  2009         0
1063  SOGELNH12AB017F92C               Love vs. Money: Part 2  ...     0         0

[5 rows x 6 columns]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


song_id                                title  ...  year user_like
245   SOSZNRJ12A8AE46E38                  Anyone Else But You  ...  2007         0
412   SOGKGLB12A81C22AFA                  Drunk and Hot Girls  ...  2007         0
484   SOQBGZD12AB0184341                        Rewind (Demo)  ...     0         0
809   SOOLSML12A8C1414DC  Don't Upset The Rhythm (Go Baby Go)  ...  2009         0
1063  SOGELNH12AB017F92C               Love vs. Money: Part 2  ...     0         0

[5 rows x 6 columns]

In [0]:
print(songs)

['SOAAAGQ12A8C1420C8', 'SOAAEJI12AB0188AB5', 'SOAAFAC12A67ADF7EB', 'SOAARXR12A8C133D15', 'SOAATLI12A8C13E319', 'SOAAUKC12AB017F868', 'SOAAVUV12AB0186646', 'SOAAWEE12A6D4FBEC8', 'SOABHYV12A6D4F6D0F', 'SOABJBU12A8C13F63F', 'SOABJTC12A58A7DE0E', 'SOABNLP12A6D4F87F4', 'SOABOXV12AC3DF82F7', 'SOABRAB12A6D4F7AAF', 'SOABTTR12A6D4FC2EB', 'SOACIPG12A8AE47E1C', 'SOACKIA12A6D4F73D7', 'SOACNQJ12A8C13B09E', 'SOACPBY12A8C13FEF9', 'SOACYKU12A5891CC64', 'SOACYUL12A6D4F9C79', 'SOADFMR12A6701FB5F', 'SOADISH12AB018DFAC', 'SOADJGO12AB0185D5B', 'SOADJQJ12A8C141D38', 'SOADMKP12A8C13BAA4', 'SOADMTV12A6701FA3F', 'SOADOQJ12A8AE45C7E', 'SOADOVQ12AB01797EB', 'SOADQPP12A67020C82', 'SOAECLL12A58A7E668', 'SOAEGIH12A6D4F8B51', 'SOAEHEX12A8C13EFA4', 'SOAEIDM12A6D4F8463', 'SOAEYBP12AB0184573', 'SOAFAXA12A58A7BB11', 'SOAFBKA12A58A7ACCF', 'SOAFHIF12AB0184446', 'SOAFKAJ12AB0181B91', 'SOAFLLJ12A8C133C8D', 'SOAFPPR12A8AE46454', 'SOAFPSO12AF72A4521', 'SOAFQGA12A8C1367FA', 'SOAFTRR12AF72A8D4D', 'SOAGFFD12AC909761F', 'SOAGGLN1

In [0]:
#songs_dataframe_unique = pd.DataFrame(songs ,columns)
#songs_dataframe_unique.head()

In [0]:
new_song_df_2 = req_songs.drop_duplicates(subset='song_id')
new_song_df_2.shape

(5175, 6)

(5175, 6)

In [0]:
new_song_df_2 = new_song_df_2.sort_values('song_id')

In [0]:
new_song_df_2.head()

song_id                         title  ...  year user_like
694887  SOAAAGQ12A8C1420C8                     Orgelblut  ...  2008         0
624717  SOAAEJI12AB0188AB5                  Godlovesugly  ...     0         0
121291  SOAAFAC12A67ADF7EB    Rome Wasn't Built In A Day  ...  2000         0
725034  SOAARXR12A8C133D15          Aunt Eggma Blowtorch  ...  1995         0
19566   SOAATLI12A8C13E319  Love Don't Live Here Anymore  ...  1978         0

[5 rows x 6 columns]

song_id                         title  ...  year user_like
694887  SOAAAGQ12A8C1420C8                     Orgelblut  ...  2008         0
624717  SOAAEJI12AB0188AB5                  Godlovesugly  ...     0         0
121291  SOAAFAC12A67ADF7EB    Rome Wasn't Built In A Day  ...  2000         0
725034  SOAARXR12A8C133D15          Aunt Eggma Blowtorch  ...  1995         0
19566   SOAATLI12A8C13E319  Love Don't Live Here Anymore  ...  1978         0

[5 rows x 6 columns]

In [0]:
new_song_df_2.to_csv('songs.csv',header =None,index=None)
bbbb= pd.read_csv('songs.csv',header=None)


In [0]:
print(bbbb.shape,'\n',bbbb)


(5175, 6) 
                        0  ...  5
0     SOAAAGQ12A8C1420C8  ...  0
1     SOAAEJI12AB0188AB5  ...  0
2     SOAAFAC12A67ADF7EB  ...  0
3     SOAARXR12A8C133D15  ...  0
4     SOAATLI12A8C13E319  ...  0
5     SOAAUKC12AB017F868  ...  0
6     SOAAVUV12AB0186646  ...  0
7     SOAAWEE12A6D4FBEC8  ...  0
8     SOABHYV12A6D4F6D0F  ...  0
9     SOABJBU12A8C13F63F  ...  0
10    SOABJTC12A58A7DE0E  ...  0
11    SOABNLP12A6D4F87F4  ...  0
12    SOABOXV12AC3DF82F7  ...  0
13    SOABRAB12A6D4F7AAF  ...  0
14    SOABTTR12A6D4FC2EB  ...  0
15    SOACIPG12A8AE47E1C  ...  0
16    SOACKIA12A6D4F73D7  ...  0
17    SOACNQJ12A8C13B09E  ...  0
18    SOACPBY12A8C13FEF9  ...  0
19    SOACYKU12A5891CC64  ...  0
20    SOACYUL12A6D4F9C79  ...  0
21    SOADFMR12A6701FB5F  ...  0
22    SOADISH12AB018DFAC  ...  0
23    SOADJGO12AB0185D5B  ...  0
24    SOADJQJ12A8C141D38  ...  0
25    SOADMKP12A8C13BAA4  ...  0
26    SOADMTV12A6701FA3F  ...  0
27    SOADOQJ12A8AE45C7E  ...  0
28    SOADOVQ12AB01797EB  ...  

#Making 2d list

In [0]:
def convert(data):
  new_data=[]
  for id_user in users:
    id_songs = data.iloc[:,1][data.iloc[:,0]==id_user]
    #print(id_songs.head())
    id_ratings = data.iloc[:,2][data.iloc[:,0]==id_user]
    #print(id_ratings.head())
    ratings = np.zeros(no_songs)
    if(id_songs.empty==False):
      for sid,rat in zip(id_songs,id_ratings):
        #print(sid)
        indx=songs.index(str(sid))
        ratings[indx] = rat
      new_data.append(list(ratings))
  return new_data

In [0]:
train_set = convert(songs_data)
#test_set = convert(songs_data_test) make test data by train test split

#not converting to torch tnsors

In [0]:
#training_set = torch.FloatTensor(train_set)
training_set = np.array(train_set)
#test_set = torch.FloatTensor(test_set)


#Convert training set (not herd to -1)

In [0]:
training_set[training_set == 0] ==-1
training_set[training_set == 1] ==0
training_set[training_set == 2] ==0
training_set[training_set > 2] ==1

array([False, False, False, ..., False, False, False])

array([False, False, False, ..., False, False, False])

In [0]:
print(training_set)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


#RBM class

In [0]:
class RBM():
  def __init__(self,nv,nh):
    #self.W = torch.randn(nh,nv)
    #self.a = torch.randn(1,nh)
    #self.b = torch.randn(1,nv)
    self.W = np.random.randn(nh,nv)
    self.a = np.random.randn(1,nh)
    self.b = np.random.randn(1,nv)
  def sample_h(self,x):
    #wx = torch.mm(x,self.W.t())
    wx = np.matmul(x,self.W.T)
    print('x X W.T =',x.shape,self.W.T.shape)
    #activation = wx + self.a.expand_as(wx)
    activation = wx + self.a
    #p_h_given_v = torch.sigmoid(activation)
    p_h_given_v = self.sigmoid(activation)
    p_h_given_v_bin = (p_h_given_v>0.5).astype(np.int_())
    return p_h_given_v, p_h_given_v_bin #replacing torch.bernoulli(p_h_given_v)
  
  def sigmoid(seld,x):
    return 1./(1. + np.exp(-x))
  
  def sample_v(self,y):
    #wy = torch.mm(y,self.W)
    wy = np.matmul(y,self.W)
    print('y X W =',y.shape,self.W.shape)
    #activation = wy + self.b.expand_as(wy)
    activation = wy + self.b
    #p_v_given_h = torch.sigmoid(activation)
    p_v_given_h = self.sigmoid(activation)
    p_v_given_h_bin = (p_v_given_h > 0.5).astype(np.int_())
    return p_v_given_h, p_v_given_h_bin #torch.bernoulli(p_v_given_h)
  
  def train(self, v0,vk,ph0,phk):
    #self.W += (torch.mm(v0.t(),ph0) - torch.mm(vk.t(),phk)).t()
    #self.b += torch.sum((v0 - vk), 0)
    #self.a += torch.sum((ph0 - phk), 0)
    self.W += (np.matmul(v0.T,ph0) - np.matmul(vk.T,phk)).T
    self.b += np.sum((v0 - vk), 0)
    self.a += np.sum((ph0 - phk), 0)
    
  def returnWeight_W(self):
    return self.W
  def returnWeight_b(self):
    return self.b
  def returnWeight_a(self):
    return self.a

In [0]:
nv = no_songs
nh  = 100
batch_size = 100
rbm = RBM(nv,nh)

#Training the model

In [0]:

nb_epoch =20
for epoch in range(1,nb_epoch + 1):
  train_loss =0
  s=0.
  for id_user in range(0,no_users-batch_size,batch_size):
    vk=v0=training_set[id_user:id_user+batch_size]
    ph0,_ = rbm.sample_h(v0)
    for k in range(10): #k step contrastive divergence
      _,hk = rbm.sample_h(vk)
      _,vk = rbm.sample_v(hk)
      vk[v0<0] = v0[v0<0]
    phk,_ = rbm.sample_h(vk)
    rbm.train(v0,vk,ph0,phk)
    #train_loss += torch.mean( torch.abs( v0[v0>=0] - vk[v0>=0] ) )
    train_loss += np.mean( np.abs( v0[v0>=0] - vk[v0>=0] ) )
    s +=1.
  print('epoch: '+str(epoch) + ' loss ' + str(train_loss/s))

x X W.T = (100, 5175) (5175, 100)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
x X W.T = (100, 5175) (5175, 100)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: overflow encountered in exp


x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
x X W.T = (100, 5175) (5175, 100)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: overflow encountered in exp


x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
x X W.T = (100, 5175) (5175, 100)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) (5175, 100)
y X W = (100, 100) (100, 5175)
x X W.T = (100, 5175) 

#Savaing file to local temp drive

In [0]:
weight_W=rbm.returnWeight_W()
weight_b = rbm.returnWeight_b()
weight_a = rbm.returnWeight_a()

In [0]:
print(weight_b,weight_b.shape)

[[ -0.20510019 -78.88244225 -18.32663418 ... -73.06847532 -34.43098145
  -34.78216811]] (1, 5175)
[[ -1.20362426 -24.54842251 -57.33177103 ... -46.79781816 -28.17570388
  -85.97384451]] (1, 5175)


In [0]:
print(weight_a)

[[ -647.91027677  -647.7525562  -2569.12833504 -2555.29945827
   -646.74020504  -654.3997973   -143.35549423 -1266.45292786
   -140.96251297 -2382.79023878 -1479.13362824  -995.50106805
  -2544.92843146 -2557.17939607 -2581.9679784  -2579.64355002
   -632.30092169 -2545.27914646  -624.0844938   -721.71084835
  -2579.4672028  -2520.16316189  -161.46407969  -655.50753461
  -2575.04783943 -2470.86232336 -2155.66319336  -157.61842729
   -131.29344722  -640.3459805   -647.80838124  -646.41632266
  -2586.53163877  -642.26763174  -118.56976251  -157.8149321
   -142.62428094  -145.19929871 -2552.81564546  -649.29227548
   -655.54255271  -624.62871596 -2410.74748192 -2305.92225162
  -1215.4808761  -2301.07203025  -648.82172097 -2317.43461938
   -143.21733629  -141.6364679   -647.83042727 -2244.6630804
   -622.33609793  -151.20014343  -195.090851    -169.54421768
   -689.42689255  -649.33502202  -101.66180913 -1114.33420519
  -2530.97421829  -725.36140914 -2408.05180095  -700.74942196
  -2608.77

In [0]:
print(weight_W)

[[ -98.58328365   -2.92531989  -57.61230003 ... -102.21846201
   -99.64213267  -53.45019707]
 [ -87.10650146    0.9015652   -54.02670127 ...  -91.23346063
   -88.57396708  -48.05453713]
 [ -92.20993957    0.47541435  -56.15628353 ...  -94.83755323
   -92.99321776  -50.59858936]
 ...
 [   1.92668547   -0.6329809   -24.69794866 ...  -40.74252412
   -38.97712745  -19.01578429]
 [ -97.44066013   -3.3584277   -57.90586742 ...  -98.50285714
   -98.15683841  -54.23232173]
 [ -90.92274715   -0.14544218  -58.57315114 ...  -99.42825516
   -98.70853323  -54.80099283]]
[[-101.84480154  -41.93455281  -94.9626794  ...  -77.24820983
   -97.30796315  -19.56017853]
 [ -98.2489283   -40.24065772  -92.07296381 ...  -70.40492927
   -92.06758476  -16.91160517]
 [ -95.88783115  -42.15773802  -95.78195088 ...  -76.33603504
   -98.37940151  -19.16343918]
 ...
 [-101.03652226  -23.09617257  -48.87355489 ...  -39.85276529
   -50.76319002   -9.61692355]
 [-100.46041247  -44.86282477  -97.99151434 ...  -76.535671

In [0]:
print(weight_a.size,weight_b.size)

100 5175
100 5175


In [0]:
#print(row_a)

In [0]:
row_a = pd.DataFrame(weight_a)
row_a.to_csv('weight_a.csv',header =None,index=None)
bbbb= pd.read_csv('weight_a.csv',header=None)
print(bbbb.size,'\n',bbbb)

100 
            0           1            2   ...          97          98          99
0 -647.910277 -647.752556 -2569.128335  ... -626.403159 -150.988312 -149.016723

[1 rows x 100 columns]
100 
            0           1            2   ...          97          98          99
0 -133.338039 -152.550335 -2998.503541  ... -552.555387 -153.505281 -153.605168

[1 rows x 100 columns]


In [0]:
row_b = pd.DataFrame(weight_b)
row_b.to_csv('weight_b.csv',header =None,index=None)
bbbb= pd.read_csv('weight_b.csv',header=None)
print(bbbb.size,'\n',bbbb)

5175 
      0          1          2     ...       5172       5173       5174
0 -0.2051 -78.882442 -18.326634  ... -73.068475 -34.430981 -34.782168

[1 rows x 5175 columns]
5175 
        0          1          2     ...       5172       5173       5174
0 -1.203624 -24.548423 -57.331771  ... -46.797818 -28.175704 -85.973845

[1 rows x 5175 columns]


In [0]:
row_w = pd.DataFrame(weight_W)
row_w.to_csv('weight_W.csv',header =None,index=None)
bbbb= pd.read_csv('weight_W.csv',header=None)
print(bbbb.shape,'\n',bbbb)

(100, 5175) 
          0         1          2     ...        5172        5173       5174
0  -98.583284 -2.925320 -57.612300  ... -102.218462  -99.642133 -53.450197
1  -87.106501  0.901565 -54.026701  ...  -91.233461  -88.573967 -48.054537
2  -92.209940  0.475414 -56.156284  ...  -94.837553  -92.993218 -50.598589
3  -46.759899  0.514217 -26.043019  ...   12.039137  -46.398815 -19.624997
4  -91.371328 -1.368271 -58.553306  ...  -99.593344  -97.636956 -53.935157
5  -94.514165 -0.511788 -58.700902  ...  -97.453397  -96.219892 -52.499637
6  -91.737834 -1.535837 -57.757341  ...  -98.011431 -100.252200 -54.428325
7   48.859494  0.407607 -23.637315  ...  -37.234801  -37.646154 -17.354743
8  -89.587305 -2.457873 -56.912894  ...  -96.575940  -95.415169 -51.960966
9  -55.953995  0.226501 -35.022144  ...  -56.124374  -55.347879 -29.222940
10 -25.872919 -0.480247 -58.601523  ... -101.145126 -100.708665 -53.029273
11   1.945492 -2.427100 -29.661078  ...  -60.582806  -60.692839 -35.195477
12 -86.2939

#(Beta) Testing the model by making

In [0]:
# predictions = []
# s = 0.
# for id_user in range(no_users):
#   v = training_set[id_user:id_user + 1]
#   vt = training_set[id_user:id_user+1]
#   if len(vt[vt>=0]) > 0:
#     _,h = rbm.sample_h(v)
#     _,v = rbm.sample_v(h)
#     pred_id = torch.sum(torch.abs(vt-v))
#     predictions.append(pred_id)
#     #test_loss += torch.mean(torch.abs(vt[vt>=0] - v[vt>=0]))
#     #s += 1.
# #print('test loss: ' + str(test_loss/s))
# plt.plot(predictions)
# plt.show
